# Generated by Django 2.2.11 on 2020-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200323_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.CharField(max_length=101),
        ),
    ]
