# Generated by Django 2.2.11 on 2020-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200323_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='presentee',
            new_name='presente',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='hora_chegada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='hora_saida',
            field=models.TimeField(),
        ),
    ]
