# Generated by Django 2.2.11 on 2020-03-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobre_nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
                ('hora_chegada', models.TimeField()),
                ('hora_saida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_chegada', models.TimeField(null=True)),
                ('hora_saida', models.TimeField(null=True)),
                ('saida_almoço', models.TimeField()),
                ('entrada_almoço', models.TimeField()),
                ('presente', models.BooleanField()),
                ('id_Funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponto.tasks.Funcionario')),
            ],
        ),
    ]
