# Generated by Django 2.2.11 on 2020-03-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200323_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='hora_chegada',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='hora_saida',
            field=models.TimeField(null=True),
        ),
    ]
